public class Inboundcallcontroller {
   

  /*  public Inboundcallcontroller(ApexPages.StandardController controller) {

  

   


 list< Inbound_Call_Report__c>       icr = [select Name,  Customer_Name__c, Phone_Number__c, Mill_Name__c, Mill_Address__c, 
         Call_Receipt_Date__c, Call_Acknowledged_By__c, Call_Classification__c, Call_Details__c
                 from Inbound_Call_Report__c
         ];

      }
   */  
}