public class LogoutCapture {
    /*
         @AuraEnabled public static void updateGeolocation(Id attendanceId, Decimal lat, Decimal lng) {
        Attendance__c attendanceRecord = [SELECT Id,Logout_Longitude__c,Logout_Latitude__c FROM Attendance__c WHERE Id = :attendanceId ];
        attendanceRecord.Logout_Latitude__c = lat;
        attendanceRecord.Logout_Longitude__c = lng;
        system.debug('Thank You for your service');
        system.debug('Have a Nice Day.');
        
             if(lat != null && lng != null){
                 
                 attendanceRecord.LogOut_Datetime__c = datetime.now();
             }
             update attendanceRecord;
         }
*/
}